production:
  sessions:
    default:
      database: server_ctrl_production
      hosts:
        - localhost:27017
      options:
        read: primary
  options:
development:
  sessions:
    default:
      database: server_ctrl_development
      hosts:
        - localhost:27017
      options:
        read: primary
  options:
test:
  sessions:
    default:
      database: server_ctrl_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
